name: gridlock
favicon: null
layout_spectrum: 0.9343493331689388
typography_spectrum: 0.4198522507213056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09882450848817825
  lightness: 0.7803399709518999
  saturation: 0.07936997059732676
  rhythmicContrast: 0.38043891196139157
purpose: []
